language: python
required: sudo
python:
  - "2.7"
  - "3.5"
  - "3.6"
virtualenv:
    system_site_packages: true
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
install:
  - sudo apt-get install python-tk python3-tk
  - python -m pip install coverage codecov
  - python3 -m pip install coverage codecov
script:
  - python -m pip install .
  - python3 -m pip install .
  - python -m nose
  - python3 -m nose
after_success:
  - coverage run nosetests
  - codecov
